/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		AppBreadcrumb: typeof import("./src/components/viewComponents/AppBreadcrumb.vue")["default"];
		AppFooter: typeof import("./src/components/viewComponents/AppFooter.vue")["default"];
		AppHeader: typeof import("./src/components/viewComponents/AppHeader.vue")["default"];
		AppSidebar: typeof import("./src/components/viewComponents/AppSidebar.vue")["default"];
		ArknightsParticle: typeof import("./src/components/articleComponents/specific/chattering/helloWorld/ArknightsParticle.vue")["default"];
		ArticleAnchor: typeof import("./src/components/articleComponents/common/ArticleAnchor.vue")["default"];
		ArticleCard: typeof import("./src/components/articleComponents/common/ArticleCard.vue")["default"];
		ArticleCodeCard: typeof import("./src/components/articleComponents/common/ArticleCodeCard.vue")["default"];
		ArticleContent: typeof import("./src/components/articleComponents/common/ArticleContent.vue")["default"];
		ArticleDate: typeof import("./src/components/articleComponents/common/ArticleDate.vue")["default"];
		ArticleFloatButton: typeof import("./src/components/articleComponents/common/ArticleFloatButton.vue")["default"];
		ArticleGlowBreath: typeof import("./src/components/articleComponents/common/ArticleGlowBreath.vue")["default"];
		ArticleGlowContainer: typeof import("./src/components/articleComponents/common/ArticleGlowContainer.vue")["default"];
		ArticleImageCaption: typeof import("./src/components/articleComponents/common/ArticleImageCaption.vue")["default"];
		ArticleIndex: typeof import("./src/components/articleComponents/common/ArticleIndex.vue")["default"];
		ArticleMermaid: typeof import("./src/components/articleComponents/common/ArticleMermaid.vue")["default"];
		ArticleParticleBackground: typeof import("./src/components/articleComponents/common/ArticleParticleBackground.vue")["default"];
		ArticleShare: typeof import("./src/components/articleComponents/common/ArticleShare.vue")["default"];
		ArticleTag: typeof import("./src/components/articleComponents/common/ArticleTag.vue")["default"];
		ArticleTextIcon: typeof import("./src/components/articleComponents/common/ArticleTextIcon.vue")["default"];
		ArticleTitle: typeof import("./src/components/articleComponents/common/ArticleTitle.vue")["default"];
		Canvas01: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas01.vue")["default"];
		Canvas02: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas02.vue")["default"];
		Canvas03: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas03.vue")["default"];
		Canvas04: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas04.vue")["default"];
		Canvas05: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas05.vue")["default"];
		Canvas06: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas06.vue")["default"];
		Canvas07: typeof import("./src/components/articleComponents/specific/learning/canvasBasic/Canvas07.vue")["default"];
		D3js01: typeof import("./src/components/articleComponents/specific/learning/d3jsBasic/D3js01.vue")["default"];
		FooterIconButton: typeof import("./src/components/articleComponents/common/FooterIconButton.vue")["default"];
		MotionConicGradientPointer: typeof import("./src/components/articleComponents/specific/chattering/helloWorld/MotionConicGradientPointer.vue")["default"];
		MotionReorderAnimation: typeof import("./src/components/articleComponents/specific/chattering/helloWorld/MotionReorderAnimation.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		TechStackIcon: typeof import("./src/components/articleComponents/specific/appHome/TechStackIcon.vue")["default"];
	}
}
