/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/viewComponents/AppBreadcrumb.vue')['default']
    AppFooter: typeof import('./src/components/viewComponents/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/viewComponents/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/viewComponents/AppSidebar.vue')['default']
    ArknightsParticle: typeof import('./src/components/articleComponents/specific/chattering/helloWorld/ArknightsParticle.vue')['default']
    ArticleDate: typeof import('./src/components/articleComponents/common/ArticleDate.vue')['default']
    ArticleFloatButton: typeof import('./src/components/articleComponents/common/ArticleFloatButton.vue')['default']
    ArticleImageCaption: typeof import('./src/components/articleComponents/common/ArticleImageCaption.vue')['default']
    ArticleLatex: typeof import('./src/components/articleComponents/common/ArticleLatex.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MotionConicGradientPointer: typeof import('./src/components/articleComponents/specific/chattering/helloWorld/MotionConicGradientPointer.vue')['default']
    MotionReorderAnimation: typeof import('./src/components/articleComponents/specific/chattering/helloWorld/MotionReorderAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
