export {default as code_01_vue3} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_01_vue3.code?raw'
export {default as code_01_html} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_01_html.code?raw'
export {default as code_01_javascript} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_01_javascript.code?raw'
export {default as code_02} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_02.code?raw'
export {default as code_03} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_03.code?raw'
