export {default as code_01} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_01.code?raw'
export {default as code_02} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_02.code?raw'
export {default as code_03_vue3} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_03_vue3.code?raw'
export {default as code_03_html} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_03_html.code?raw'
export {default as code_03_javascript} from '@/components/articleComponents/specific/learning/canvasBasic/codes/code_03_javascript.code?raw'
