export { default as code_01 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_01.code?raw";
export { default as code_02 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_02.code?raw";
export { default as code_03 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_03.code?raw";
export { default as code_04 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_04.code?raw";
export { default as code_05 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_05.code?raw";
export { default as code_06 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_06.code?raw";
export { default as code_07 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_07.code?raw";
export { default as code_08 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_08.code?raw";
export { default as code_09 } from "@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_09.code?raw";
