export {default as code_01} from '@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_01.code?raw'
export {default as code_02} from '@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_02.code?raw'
export {default as code_03} from '@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_03.code?raw'
export {default as code_04} from '@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_04.code?raw'
export {default as code_05} from '@/components/articleComponents/specific/learning/typescriptKnowledge/codes/code_05.code?raw'
